resource_types:
- name: slack_notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

#- name: twitter_notification
#  type: docker-image
#  source:
#    repository: ecsteam/twitter-concourse-resource


resources:
- name: app_sources
  type: git
  source:
    uri: https://github.com/smichard/CloudFoundryDemo
    branch: master

- name: staging_CloudFoundry
  type: cf
  source:
    api: {{pws_api}}
    username: {{pws_user}}
    password: {{pws_password}}
    organization: {{pws_org}}
    space: {{pws_space}}
    skip_cert_check: false

- name: tracker_output
  type: tracker
  source:
    token: {{traker_api_token}}
    project_id: "2098312"
    tracker_url: https://www.pivotaltracker.com

#- name: s3_target
#  type: s3
#  source:
#    endpoint: {{s3_endpoint}}
#    bucket: releases
#    regexp: directory_on_s3/release-(.*).tgz tbd
#    access_key_id: {{s3_key}}
#    secret_access_key: {{s3_secret}}

- name: slack_msg
  type: slack_notification
  source:
    url: {{slack_hook}}

#- name: twitter_msg
#  type: twitter_notification
#  source:
#    consumer_key: {{twitter_consumer_key}}
#    consumer_secret: {{twitter_consumer_secret}}
#    access_token: {{twitter_access_token}}
#    access_token_secret: {{twitter_access_token_secret}}

jobs:
- name: deploy-website
  public: true
  serial: true
  plan:
  - get: app_sources
    trigger: true
  - put: staging_CloudFoundry
    params:
        manifest: app_sources/manifest.yml
  - put: slack_msg
    params:
      channel: '#general'
      text: The new version was successfully pushed to Cloud Foundry.
  - put: tracker_output
    params:
      repos:
      - app_sources
#  - put: s3_target
#    params:
#      file: tbd
#      acl: public-read
#  - put: twitter_msg
#    params:
#      status: >
#        Just deployed a new version of my app to Cloud Foundry with @concourseci (Build ${BUILD_ID}) #CloudFoundry #CloudNative

#bla
