---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: getourneau/alpine-bash-git
inputs:
  - name: app_sources_production
  - name: app_sources_staging
outputs:
  - name: out
run:
  path: /bin/bash
  args:
  - app_sources_staging/ci/tasks/merge-release-branch.sh
