resources:
- name: repo-master
  type: git
  source:
    uri: http://github.com/smichard/CloudFoundryDemo
    branch: master
  check_every: 30s
  webhook_token: bladibladibla

- name: cloud_foundry
  type: cf
  source:
    api: {{cf_api}}
    username: {{cf_user}}
    password: {{cf_password}}
    organization: {{cf_org}}
    space: {{cf_space_production}}
    skip_cert_check: false

jobs:
  - name: test-master
    public: true
    serial: true
    plan:
      - get: repo-master
        trigger: true
      - task: unit
        file: repo-master/ci/tasks/unit.yml

  - name: deploy-master
    public: true
    serial: true
    plan:
    - get: repo-master
      passed: [ test-master ]
      trigger: true
    - put: cloud_foundry
      params:
        path: repo-master/
        manifest: repo-master/manifest.yml
