resource_types:
- name: slack_notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
- name: app_sources_production
  type: git
  source:
    uri: https://github.com/smichard/CloudFoundryDemo.git
    branch: dev
    username: {{github_username}}
    password: {{github_password}}
  check_every: 30s

- name: version
  type: semver
  source:
    uri: https://github.com/smichard/CloudFoundryDemo.git
    branch: version
    username: {{github_username}}
    password: {{github_password}}
    file: version
    driver: git
    initial_version: 0.6.0

- name: cloud_foundry
  type: cf
  source:
    api: {{cf_api}}
    username: {{cf_user}}
    password: {{cf_password}}
    organization: {{cf_org}}
    space: {{cf_space_production}}
    skip_cert_check: false

- name: S3_target
  type: s3
  source:
    endpoint: {{s3_endpoint}}
    bucket: releases
    regexp: release_history/cloud_foundry_demo-(.*)-(.*).tar.gz
    access_key_id: {{s3_key}}
    secret_access_key: {{s3_secret}}

- name: slack_msg
  type: slack_notification
  source:
    url: {{slack_hook}}


jobs:
  - name: test-app
    public: true
    serial: true
    plan:
      - get: app_sources_production
        trigger: true
      - task: unit
        file: app_sources_production/ci/tasks/unit.yml

  - name: deploy-app
    public: true
    serial: true
    plan:
    - get: app_sources_production
      passed: [ test-app ]
      trigger: true
    - put: cloud_foundry
      params:
        path: app_sources_production/
        manifest: app_sources_production/manifest.yml
      on_success:
          put: slack_msg
          params:
            channel: '#general'
            text: |
              Production: The build $BUILD_JOB_NAME with build ID $BUILD_ID for pipeline $BUILD_PIPELINE_NAME completed succesfully. Check the current development state at:
              http://cloudfoundry-demo-sym.cfapps.io/
      on_failure:
          put: slack_msg
          params:
            channel: '#general'
            text: |
              Production: The build $BUILD_JOB_NAME with build ID $BUILD_ID for pipeline $BUILD_PIPELINE_NAME failed. Check it out at:
              http://127.0.0.1:8080/builds/$BUILD_ID

  - name: ecs-backup
    public: true
    serial: true
    plan:
    - get: version
      trigger: false
    - get: app_sources_production
      trigger: true
      passed: [ deploy-app ]
    - task: create-artifact
      file: app_sources_production/ci/tasks/create_artifact.yml
    - put: S3_target
      params:
        file: ./artifact/cloud_foundry_demo-*-*.tar.gz
        acl: public-read
      on_success:
        put: slack_msg
        params:
          channel: '#general'
          text: |
            Artifact succesfully uploaded to S3 target.
      on_failure:
        put: slack_msg
        params:
          channel: '#general'
          text: |
            Artifact could not be uploaded to S3 target: The build $BUILD_JOB_NAME with build ID $BUILD_ID for pipeline $BUILD_PIPELINE_NAME failed. Check it out at:
            http://127.0.0.1:8080/builds/$BUILD_ID
