resource_types:
- name: slack_notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

- name: twitter_notification
  type: docker-image
  source:
    repository: ecsteam/twitter-concourse-resource

resources:
- name: app_sources_dev
  type: git
  source:
    uri: https://github.com/smichard/CloudFoundryDemo.git
    branch: dev
    username: {{github_username}}
    password: {{github_password}}
  check_every: 10s

- name: app_sources_staging
  type: git
  source:
    uri: https://github.com/smichard/CloudFoundryDemo.git
    branch: staging
    username: {{github_username}}
    password: {{github_password}}
  check_every: 30s

- name: app_sources_production
  type: git
  source:
    uri: https://github.com/smichard/CloudFoundryDemo.git
    branch: master
    username: {{github_username}}
    password: {{github_password}}
  check_every: 30s

- name: version
  type: semver
  source:
    uri: https://github.com/smichard/CloudFoundryDemo.git
    branch: version
    username: {{github_username}}
    password: {{github_password}}
    file: version
    driver: git
    initial_version: 0.6.0

- name: cloud_foundry_dev
  type: cf
  source:
    api: {{cf_api}}
    username: {{cf_user}}
    password: {{cf_password}}
    organization: {{cf_org}}
    space: {{cf_space_dev}}
    skip_cert_check: false

- name: cloud_foundry_staging
  type: cf
  source:
    api: {{cf_api}}
    username: {{cf_user}}
    password: {{cf_password}}
    organization: {{cf_org}}
    space: {{cf_space_staging}}
    skip_cert_check: false

- name: cloud_foundry_production
  type: cf
  source:
    api: {{cf_api}}
    username: {{cf_user}}
    password: {{cf_password}}
    organization: {{cf_org}}
    space: {{cf_space_production}}
    skip_cert_check: false

- name: tracker_output
  type: tracker
  source:
    token: {{traker_api_token}}
    project_id: {{tracker-project-id}}
    tracker_url: https://www.pivotaltracker.com

- name: ecs_backup
  type: s3
  source:
    endpoint: {{s3_endpoint}}
#    bucket: releases
#    regexp: release_history/release-(.*).tgz
    access_key_id: {{s3_key}}
    secret_access_key: {{s3_secret}}

- name: slack_msg
  type: slack_notification
  source:
    url: {{slack_hook}}

- name: twitter_msg
  type: twitter_notification
  source:
    consumer_key: {{twitter_consumer_key}}
    consumer_secret: {{twitter_consumer_secret}}
    access_token: {{twitter_access_token}}
    access_token_secret: {{twitter_access_token_secret}}


jobs:
  - name: test-dev
    public: true
    serial: true
    plan:
      - get: app_sources_dev
        trigger: true
      - task: unit
        file: app_sources_dev/ci/tasks/unit.yml
      - put: tracker_output
        params:
          repos:
          - app_sources_dev

  - name: deploy-dev
    public: true
    serial: true
    plan:
    - get: app_sources_dev
      passed: [ test-dev ]
      trigger: true
    - put: cloud_foundry_dev
      params:
        path: app_sources_dev/
        manifest: app_sources_dev/manifest_dev.yml
      on_success:
        do:
        - task: hue_green
          file: app_sources_dev/ci/tasks/hue_green.yml
        - put: slack_msg
          params:
            channel: '#general'
            text: |
              Dev: The build $BUILD_JOB_NAME with build ID $BUILD_ID for pipeline $BUILD_PIPELINE_NAME completed succesfully. Check the current development state at:
              https://cloudfoundry-demo-sym-dev.cfapps.io/
              Merge dev branch to staging branch environment:
              http://149.202.48.252:9000/hooks/trigger-merge-to-staging-pipeline?token=h32kj5hkj43hkj2h35kjh3k3hj2kjh532kjhkj4h2kjthk4308978jlkj
      on_failure:
        do:
        - task: hue_red
          file: app_sources_dev/ci/tasks/hue_red.yml
        - put: slack_msg
          params:
            channel: '#general'
            text: |
              Dev: The build $BUILD_JOB_NAME with build ID $BUILD_ID for pipeline $BUILD_PIPELINE_NAME failed. Check it out at:
              http://127.0.0.1:8080/builds/$BUILD_ID

  - name: merge-dev-to-staging
    public: true
    plan:
      - get: app_sources_dev
        passed: [ test-dev ]
        trigger: false
      - put: app_sources_staging
        params:
            repository: app_sources_dev
            merge: TRUE
        on_success:
          put: slack_msg
          params:
            channel: '#general'
            text: |
              Dev branch succesfully merged to staging branch: The build $BUILD_JOB_NAME with build ID $BUILD_ID for pipeline $BUILD_PIPELINE_NAME completed succesfully.
        on_failure:
          put: slack_msg
          params:
            channel: '#general'
            text: |
              Dev branch failed to merge with staging branch: The build $BUILD_JOB_NAME with build ID $BUILD_ID for pipeline $BUILD_PIPELINE_NAME failed. Check it out at:
              http://127.0.0.1:8080/builds/$BUILD_ID

  - name: test-staging
    public: true
    serial: true
    plan:
      - get: app_sources_staging
        passed: [ merge-dev-to-staging ]
        trigger: true
      - task: unit
        file: app_sources_staging/ci/tasks/unit.yml

  - name: deploy-staging
    public: true
    serial: true
    plan:
    - get: app_sources_staging
      passed: [ test-staging ]
      trigger: true
    - put: cloud_foundry_staging
      params:
        path: app_sources_staging/
        manifest: app_sources_staging/manifest_staging.yml
      on_success:
        do:
        - task: hue_green
          file: app_sources_staging/ci/tasks/hue_green.yml
        - put: slack_msg
          params:
            channel: '#general'
            text: |
              Staging: The build $BUILD_JOB_NAME with build ID $BUILD_ID for pipeline $BUILD_PIPELINE_NAME completed succesfully. Check the current development state at:
              https://cloudfoundry-demo-sym-staging.cfapps.io/
              Merge staging branch to master branch environment:
              http://149.202.48.252:9000/hooks/trigger-merge-to-master-pipeline?token=h32kj5hkj43hkj2h35kjh3k3hj2kjh532kjhkj4h2kjthk4308978jlkj
      on_failure:
        do:
          - task: hue_red
            file: app_sources_staging/ci/tasks/hue_red.yml
          - put: slack_msg
            params:
              channel: '#general'
              text: |
                Staging: The build $BUILD_JOB_NAME with build ID $BUILD_ID for pipeline $BUILD_PIPELINE_NAME failed. Check it out at:
                http://127.0.0.1:8080/builds/$BUILD_ID

  - name: merge-release-to-master
    public: true
    plan:
      - get: app_sources_staging
        passed: [ test-staging ]
        trigger: false
      - get: version
        trigger: false
      - put: app_sources_production
        params:
            repository: app_sources_staging
            merge: true
            tag: version/version
        on_success:
          put: slack_msg
          params:
            channel: '#general'
            text: |
              Release branch succesfully merged to master branch: The build $BUILD_JOB_NAME with build ID $BUILD_ID for pipeline $BUILD_PIPELINE_NAME completed succesfully.
        on_failure:
          put: slack_msg
          params:
            channel: '#general'
            text: |
              Release branch failed to merge with master branch: The build $BUILD_JOB_NAME with build ID $BUILD_ID for pipeline $BUILD_PIPELINE_NAME failed. Check it out at:
              http://127.0.0.1:8080/builds/$BUILD_ID

  - name: test-master
    public: true
    serial: true
    plan:
      - get: app_sources_production
        passed: [ merge-release-to-master ]
        trigger: true
      - task: unit
        file: app_sources_production/ci/tasks/unit.yml

  - name: bump-version-minor
    public: true
    plan:
      - aggregate:
        - get:  app_sources_production
          passed: [ test-master ]
          trigger: true
        - get: version
          trigger: false
        - put: version
          params: {bump: minor}

  - name: deploy-master
    public: true
    serial: true
    plan:
    - get: app_sources_production
      passed: [ test-master ]
      trigger: true
    - put: ecs_backup
      params: {file: app_sources_production/index.html}
#        file: app_sources_production/index.html
#        acl: public-read
    - put: cloud_foundry_production
      params:
        path: app_sources_production/
        manifest: app_sources_production/manifest.yml
      on_success:
        do:
          - task: hue_green
            file: app_sources_production/ci/tasks/hue_green.yml
          - put: slack_msg
            params:
              channel: '#general'
              text: |
                Production: The build $BUILD_JOB_NAME with build ID $BUILD_ID for pipeline $BUILD_PIPELINE_NAME completed succesfully. Check the current development state at:
                http://cloudfoundry-demo-sym.cfapps.io/
          - put: twitter_msg
            params:
              status: >
                Just deployed a new version of my app to Cloud Foundry with @concourseci (build ${BUILD_ID}) - check it out http://cloudfoundry-demo-sym.cfapps.io/
      on_failure:
        do:
          - task: hue_red
            file: app_sources_production/ci/tasks/hue_red.yml
          - put: slack_msg
            params:
              channel: '#general'
              text: |
                Production: The build $BUILD_JOB_NAME with build ID $BUILD_ID for pipeline $BUILD_PIPELINE_NAME failed. Check it out at:
                http://127.0.0.1:8080/builds/$BUILD_ID

  - name: patch
    public: true
    plan:
      - aggregate:
        - get: version
          trigger: false
        - put: version
          params: {bump: patch}

  - name: minor
    public: true
    plan:
      - aggregate:
        - get: version
          trigger: false
        - put: version
          params: {bump: minor}

  - name: major
    public: true
    plan:
      - aggregate:
        - get: version
          trigger: false
        - put: version
          params: {bump: major}
