resources:

- name: app_sources_production
  type: git
  source:
    uri: https://github.com/smichard/CloudFoundryDemo.git
    branch: master
    username: {{github_username}}
    password: {{github_password}}
  check_every: 30s

- name: app_sources_release
  type: git
  source:
    uri: https://github.com/smichard/CloudFoundryDemo.git
    branch: master
    username: {{github_username}}
    password: {{github_password}}
    release: true
  check_every: 30s

- name: version
  type: semver
  source:
    uri: https://github.com/smichard/CloudFoundryDemo.git
    branch: version
    username: {{github_username}}
    password: {{github_password}}
    file: version
    driver: git
    initial_version: 0.6.0

#- name: cloud_foundry_production
#  type: cf
#  source:
#    api: {{cf_api}}
#    username: {{cf_user}}
#    password: {{cf_password}}
#    organization: {{cf_org}}
#    space: {{cf_space_production}}
#    skip_cert_check: false


- name: ecs_backup
  type: s3
  source:
    endpoint: {{s32_endpoint}}
    bucket: releases
    regexp: release_history/CloudFoundryDemo-(.*).tar.gz
    access_key_id: {{s32_key}}
    secret_access_key: {{s32_secret}}


jobs:
  - name: ecs-backup
    public: true
    serial: true
    plan:
    - get: app_sources_production
#      passed: [ test-master ]
      trigger: true
    - get: app_sources_release
      trigger: false
    - get: version
      trigger: false
    - put: ecs_backup
      params: # {file: app_sources_release/CloudFoundryDemo-(.*).tar.gz}
        file: app_sources_release/index.html
        acl: public-read
